name: CI-Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: python:3.9-slim
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Installiere Abhängigkeiten
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

  lint:
    name: Lint mit flake8
    runs-on: ubuntu-latest
    container:
      image: python:3.9-slim
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Installiere Abhängigkeiten
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint ausführen
        run: |
          flake8 service --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 service --count --max-complexity=10 --max-line-length=127 --statistics

  tests:
    name: Führen Sie mit nose Unit-Tests aus
    runs-on: ubuntu-latest
    container:
      image: python:3.9-slim
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Installiere Abhängigkeiten
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Unit-Tests ausführen
        run: |
          nosetests -v --with-spec --spec-color --with-coverage --cover-package=app
